services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "8443:80"
    volumes:
      - ./data:/data
    environment:
      - TZ=America/Chicago
      - DOMAIN=https://vault.nanolab.local
      - SIGNUPS_ALLOWED=true
      - INVITATIONS_ALLOWED=true
      - LOG_LEVEL=warn
      - WEBSOCKET_ENABLED=true
